### ISSUE TITLE
what is Flickr PIN and how to get it?

### ISSUE THREAD

**Issue by norayr** [Wunderfitz/harbour-fernweh#5]
when I run it, it asks:
"Please enter the Flickr PIN:" and i have a numbers only keyboard.
what is a flickr pin? i cannot find it anywhere in flickr settings or on the web.

**Comment by Wunderfitz** [comment]
Under normal circumstances, the app should launch your browser where you need to login to Flickr and allow Fernweh to access your profile. After you have granted that, Flickr will return this PIN (some digits with hyphens). You need to enter this PIN here. It's a standard OAuth 1 OOB flow, see https://oauth.net/core/1.0a/

If your browser doesn't launch, you have an issue with your configuration. Try using https://openrepos.net/content/llelectronics/mimer to reset the browser configuration.
